package com.homato

const val JWT_SECRET_ENV = "JWT_SECRET"
const val JWT_ISSUER = "JWT_ISSUER"
const val JWT_AUDIENCE = "JWT_AUDIENCE"
const val JWT_DOMAIN = "JWT_DOMAIN"
const val JWT_REALM = "JWT_REALM"

const val BACKBLAZE_APPLICATION_KEY_ID = "BACKBLAZE_APPLICATION_KEY_ID"
const val BACKBLAZE_APPLICATION_KEY = "BACKBLAZE_APPLICATION_KEY"
const val BACKBLAZE_SPOT_MAIN_IMAGE_BUCKET_ID = "BACKBLAZE_SPOT_MAIN_IMAGE_BUCKET_ID"
const val BACKBLAZE_SPOT_VISIT_IMAGE_BUCKET_ID = "BACKBLAZE_SPOT_VISIT_IMAGE_BUCKET_ID"
const val BACKBLAZE_SPOT_MAIN_IMAGE_BUCKET_NAME = "BACKBLAZE_SPOT_MAIN_IMAGE_BUCKET_NAME"

const val POSTGRESQL_CONNECTION_STRING = "POSTGRESQL_CONNECTION_STRING"
const val POSTGRESQL_PW = "POSTGRESQL_PW"
const val POSTGRESQL_USER = "POSTGRESQL_USER"

