package com.homato

const val POSTGRESQL_PW = "POSTGRESQL_PW"
const val JWT_SECRET_ENV = "JWT_SECRET"
const val BACKBLAZE_APPLICATION_KEY_ID = "BACKBLAZE_APPLICATION_KEY_ID"
const val BACKBLAZE_APPLICATION_KEY = "BACKBLAZE_APPLICATION_KEY"
const val BACKBLAZE_SPOT_MAIN_IMAGE_BUCKET_ID = "BACKBLAZE_SPOT_MAIN_IMAGE_BUCKET_ID"
const val BACKBLAZE_SPOT_MAIN_IMAGE_BUCKET_NAME = "BACKBLAZE_SPOT_MAIN_IMAGE_BUCKET_NAME"
