package com.homato.service.authentication

import org.koin.core.annotation.Factory
import org.koin.core.component.KoinComponent

@Factory
class UsernameGenerator : KoinComponent {

    fun generateUsername(): String {
        return predefinedUsernames.random() + (1..9999).random()
    }

    private val predefinedUsernames = listOf(
        "UrbanExplorer",
        "TrailBlazer",
        "AdventureSeeker",
        "CityWanderer",
        "RoamingNomad",
        "ConcreteExplorer",
        "UrbanTrailblazer",
        "CityscapeScout",
        "ExplorerExtraordinaire",
        "WanderingNomad",
        "ConcreteJungleRover",
        "CitySafari",
        "MetroMaverick",
        "UrbaneAdventurer",
        "StreetWanderer",
        "UrbanPioneer",
        "SkylineStroller",
        "CityscapeSeeker",
        "WanderlustWalker",
        "UrbanVoyager",
        "RooftopRover",
        "UrbanAdventure",
        "StreetwiseExplorer",
        "ConcreteJungleExplorer",
        "CitySavant",
        "MetropolisNomad",
        "ExplorerEnthusiast",
        "UrbanTrekker",
        "CitySightseer",
        "RoamingRambler",
        "CityscapeSleuth",
        "ConcreteJungleNomad",
        "MetroMaverick",
        "UrbanJourneyman",
        "CityWanderlust",
        "UrbanExplorerX",
        "ConcreteSafari",
        "CityscapeVoyager",
        "UrbanNomad",
        "CityTrekker",
        "UrbanRoamer",
        "StreetSafari",
        "ConcreteWanderer",
        "UrbanVenturer",
        "CityscapeChaser",
        "UrbanEpicurean",
        "MetroExplorer",
        "CitySafari",
        "UrbanRamblin",
        "RoamingVoyager",
        "UrbanWanderer",
        "ConcreteNomad",
        "CityscapeScavenger",
        "WandererInMetropolis",
        "UrbanTrailSeeker",
        "StreetSleuth",
        "CityExplorer",
        "UrbanNomad",
        "RooftopExplorer",
        "UrbanAdventurer",
        "CitySightseer",
        "ConcreteTrekker",
        "UrbanVagabond",
        "CityscapeWanderer",
        "MetroMarauder",
        "CityStroller",
        "UrbanRover",
        "StreetwiseSeeker",
        "ConcreteSleuth",
        "UrbanDiscoverer",
        "CitySavvy",
        "RooftopRambler",
        "UrbanJungleNomad",
        "MetroMaverick",
        "CityscapeWanderlust",
        "UrbanTrekkerX",
        "ConcreteAdventurer",
        "CitySightseeingNomad",
        "UrbanRoamer",
        "StreetSavvy",
        "CityscapeVoyager",
        "UrbanExplorer",
        "RooftopRover",
        "UrbanNomadX",
        "ConcreteCrawler",
        "CitySleuth",
        "UrbanTrailblazer",
        "StreetwiseScout",
        "CityExplorerX",
        "UrbanSafari",
        "RooftopRambler",
        "UrbanPioneer",
        "ConcreteNomad",
        "CityscapeStroller"
    )

}